apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:
    name: mysql-volume
spec:
  containers:
  - name: mysqlvolume
    image: mysql
    env: 
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: data-volume
    ports:
      - containerPort: 3306
        name: mysql
  volumes:
  - name: data-volume
    hostPath:
      path: /data-volume
      type: Directory
