apiVersion: v1
kind: Pod
metadata: 
  name: my-simple-webapp
spec:
  containers:
  - name: simple-webapp-color
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: red