apiVersion: v1
kind: Pod
metadata:
  name: myapp-webapp-color-red
  labels:
    app: web
spec:
  containers:
  - name: myapp
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
    env: 
    - name: APP_COLOR
      value: red
